DROP DATABASE IF EXISTS employee_db;
CREATE DATABASE employee_db;

USE employee_db;

CREATE TABLE deparment (
id INTEGER AUTO_INCREMENT NOT NULL,
PRIMARY KEY (id),
dept_name VARCHAR(30)
);

CREATE TABLE role (
id INTEGER AUTO_INCREMENT NOT NULL,
PRIMARY KEY (id),
title VARCHAR(30),
salary DECIMAL,
department_id INTEGER NOT NULL
);

CREATE TABLE employee (
id INTEGER AUTO_INCREMENT NOT NULL,
PRIMARY KEY (id),
first_name VARCHAR(30),
last_name VARCHAR(30),
role_id INTEGER NOT NULL,
manager_id INTEGER
);